eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.110:8762/eureka/, http://192.168.2.244:8763/eureka/, http://192.168.2.161:8764/eureka
    fetch-registry: true
    register-with-eureka: true
spring:
  rabbitmq:
  host: 192.168.2.244
  port: 5672
  virtual-host: /
  username: test
  password: test
