spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SpringCloud_sell?characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Azjx0813!
  rabbitmq:
    host: 192.168.2.244
    port: 5672
    virtual-host: /
    username: test
    password: test
  redis:
    host: localhost
    port: 6379
    password: redis
eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.110:8762/eureka/, http://192.168.2.244:8763/eureka/, http://192.168.2.161:8764/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*.xml
as:
  ma
