server:
  port: 10010
logging:
  level:
    root: INFO
    top.asia.product.mapper: TRACE
    org.springframework.amqp: DEBUG
    org.springframework.amqp.rabbit: DEBUG
    org.springframework.cloud.bus: DEBUG
boy:
  name: mayazhou
  age: 120
